# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Gabriel Gularte <ggularte@3c.gg>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-24 21:28-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"msgid Project-Id-Version: PACKAGE VERSION\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: accounts/api/controller.py:80
#, fuzzy
#| msgid "User already has an account"
msgid "User already has an account."
msgstr "User already has an account."

#: accounts/api/controller.py:85 matchmaking/models/lobby.py:271
msgid "User must be invited."
msgstr "User must be invited."

#: accounts/models/account.py:34
msgid "Steam account not found."
msgstr "Steam account not found."

#: accounts/models/account.py:92
#, python-brace-format
msgid "Maximum invites reached ({self.MAX_INVITES_PER_ACCOUNT})."
msgstr "Maximum invites reached ({self.MAX_INVITES_PER_ACCOUNT})."

#: accounts/models/account.py:96
msgid "Accepted invites cannot be modified."
msgstr "Accepted invites cannot be modified."

#: accounts/models/account.py:99
msgid "An invite already exists for this email."
msgstr "An invite already exists for this email."

#: appsettings/models.py:7
msgid "Text"
msgstr "Text"

#: appsettings/models.py:8
msgid "Integer"
msgstr "Integer"

#: appsettings/models.py:9
msgid "Boolean"
msgstr "Boolean"

#: core/api/pydantic_messages.py:4
msgid "field required"
msgstr "Field required."

#: core/api/pydantic_messages.py:5
msgid "extra fields not permitted"
msgstr "Extra fields not permitted."

#: core/api/pydantic_messages.py:6
msgid "none is not an allowed value"
msgstr "None is not an allowed value."

#: core/api/pydantic_messages.py:7
msgid "value is not none"
msgstr "Value is not none."

#: core/api/pydantic_messages.py:8
msgid "value is not None"
msgstr "Value is not None."

#: core/api/pydantic_messages.py:10
msgid "value could not be parsed to a boolean"
msgstr "Value could not be parsed to a boolean."

#: core/api/pydantic_messages.py:12
msgid "byte type expected"
msgstr "Byte type expected."

#: core/api/pydantic_messages.py:13
msgid "value is not a valid dict"
msgstr "Value is not a valid dict."

#: core/api/pydantic_messages.py:14
msgid "value is not a valid email address"
msgstr "Value is not a valid email address."

#: core/api/pydantic_messages.py:15
msgid "invalid or missing URL scheme"
msgstr "Invalid or missing URL scheme."

#: core/api/pydantic_messages.py:16
msgid "URL scheme not permitted"
msgstr "URL scheme not permitted."

#: core/api/pydantic_messages.py:17
msgid "userinfo required in URL but missing"
msgstr "Userinfo required in URL but missing."

#: core/api/pydantic_messages.py:18
msgid "URL host invalid"
msgstr "URL host invalid."

#: core/api/pydantic_messages.py:20
msgid "URL host invalid, top level domain required"
msgstr "URL host invalid, top level domain required."

#: core/api/pydantic_messages.py:23
msgid "URL port invalid, port cannot exceed 65535"
msgstr "URL port invalid, port cannot exceed 65535."

#: core/api/pydantic_messages.py:26
msgid "URL invalid, extra characters found after valid URL: {}"
msgstr "URL invalid, extra characters found after valid URL: {}."

#: core/api/pydantic_messages.py:28
msgid "{} is not a valid Enum instance"
msgstr "{} is not a valid Enum instance."

#: core/api/pydantic_messages.py:29
msgid "{} is not a valid IntEnum instance"
msgstr "{} is not a valid IntEnum instance."

#: core/api/pydantic_messages.py:30
msgid "value is not a valid integer"
msgstr "Value is not a valid integer."

#: core/api/pydantic_messages.py:31
msgid "value is not a valid float"
msgstr "Value is not a valid float."

#: core/api/pydantic_messages.py:32
msgid "value is not a valid path"
msgstr "Value is not a valid path."

#: core/api/pydantic_messages.py:34
msgid "file or directory at path \"{}\" does not exist"
msgstr "File or directory at path \"{}\" does not exist."

#: core/api/pydantic_messages.py:36
msgid "path \"{}\" does not point to a file"
msgstr "Path \"{}\" does not point to a file."

#: core/api/pydantic_messages.py:38
msgid "path \"{}\" does not point to a directory"
msgstr "Path \"{}\" does not point to a directory."

#: core/api/pydantic_messages.py:41
msgid "ensure this value contains valid import path or valid callable: {}"
msgstr "Ensure this value contains valid import path or valid callable: {}."

#: core/api/pydantic_messages.py:43
msgid "value is not a valid sequence"
msgstr "Value is not a valid sequence."

#: core/api/pydantic_messages.py:44
msgid "value is not a valid list"
msgstr "Value is not a valid list."

#: core/api/pydantic_messages.py:45
msgid "value is not a valid set"
msgstr "Value is not a valid set."

#: core/api/pydantic_messages.py:46
msgid "value is not a valid frozenset"
msgstr "Value is not a valid frozenset."

#: core/api/pydantic_messages.py:47
msgid "value is not a valid tuple"
msgstr "Value is not a valid tuple."

#: core/api/pydantic_messages.py:48
msgid "wrong tuple length {}"
msgstr "Wrong tuple length {}."

#: core/api/pydantic_messages.py:50
msgid "ensure this value has at least {} items"
msgstr "Ensure this value has at least {} items."

#: core/api/pydantic_messages.py:53
msgid "ensure this value has at most {} items"
msgstr "Ensure this value has at most {} items."

#: core/api/pydantic_messages.py:55
msgid "the list has duplicated items"
msgstr "The list has duplicated items."

#: core/api/pydantic_messages.py:57
msgid "ensure this value has at least {} characters"
msgstr "Ensure this value has at least {} characters."

#: core/api/pydantic_messages.py:60
msgid "ensure this value has at most {} characters"
msgstr "Ensure this value has at most {} characters."

#: core/api/pydantic_messages.py:62
msgid "str type expected"
msgstr "Str type expected."

#: core/api/pydantic_messages.py:63
msgid "string does not match regex \"{}\""
msgstr "String does not match regex \"{}\"."

#: core/api/pydantic_messages.py:64
msgid "ensure this value is greater than {}"
msgstr "Ensure this value is greater than {}."

#: core/api/pydantic_messages.py:66
msgid "ensure this value is greater than or equal to {}"
msgstr "Ensure this value is greater than or equal to {}."

#: core/api/pydantic_messages.py:68
msgid "ensure this value is less than {}"
msgstr "Ensure this value is less than {}."

#: core/api/pydantic_messages.py:70
msgid "ensure this value is less than or equal to {}"
msgstr "Ensure this value is less than or equal to {}."

#: core/api/pydantic_messages.py:72
msgid "ensure this value is a multiple of {}"
msgstr "Ensure this value is a multiple of {}."

#: core/api/pydantic_messages.py:73
msgid "value is not a valid decimal"
msgstr "Value is not a valid decimal."

#: core/api/pydantic_messages.py:75
msgid "ensure that there are no more than {} digits in total"
msgstr "Ensure that there are no more than {} digits in total."

#: core/api/pydantic_messages.py:78
msgid "ensure that there are no more than {} decimal places"
msgstr "Ensure that there are no more than {} decimal places."

#: core/api/pydantic_messages.py:81
msgid "ensure that there are no more than {} digits before the decimal point"
msgstr "Ensure that there are no more than {} digits before the decimal point."

#: core/api/pydantic_messages.py:83
msgid "invalid datetime format"
msgstr "Invalid datetime format."

#: core/api/pydantic_messages.py:84
msgid "invalid date format"
msgstr "Invalid date format."

#: core/api/pydantic_messages.py:85
msgid "date is not in the past"
msgstr "Date is not in the past."

#: core/api/pydantic_messages.py:86
msgid "date is not in the future"
msgstr "Date is not in the future."

#: core/api/pydantic_messages.py:87
msgid "invalid time format"
msgstr "Invalid time format."

#: core/api/pydantic_messages.py:88
msgid "invalid duration format"
msgstr "Invalid duration format."

#: core/api/pydantic_messages.py:89
msgid "value is not a valid hashable"
msgstr "Value is not a valid hashable."

#: core/api/pydantic_messages.py:90
msgid "value is not a valid uuid"
msgstr "Value is not a valid uuid."

#: core/api/pydantic_messages.py:91
msgid "uuid version {} expected"
msgstr "Uuid version {} expected."

#: core/api/pydantic_messages.py:92
msgid "instance of {} expected"
msgstr "Instance of {} expected."

#: core/api/pydantic_messages.py:93
msgid "a class is expected"
msgstr "A class is expected."

#: core/api/pydantic_messages.py:94
msgid "subclass of {} expected"
msgstr "Subclass of {} expected."

#: core/api/pydantic_messages.py:95
msgid "Invalid JSON"
msgstr "Invalid JSON."

#: core/api/pydantic_messages.py:97
msgid "JSON object must be str, bytes or bytearray"
msgstr "JSON object must be str, bytes or bytearray."

#: core/api/pydantic_messages.py:99
msgid "Invalid regular expression"
msgstr "Invalid regular expression."

#: core/api/pydantic_messages.py:101
msgid "instance of {}, tuple or dict expected"
msgstr "Instance of {}, tuple or dict expected."

#: core/api/pydantic_messages.py:103
msgid "{} is not callable"
msgstr "{} is not callable "

#: core/api/pydantic_messages.py:105
msgid "value is not a valid IPv4 or IPv6 address"
msgstr "Value is not a valid IPv4 or IPv6 address."

#: core/api/pydantic_messages.py:108
msgid "value is not a valid IPv4 or IPv6 interface"
msgstr "Value is not a valid IPv4 or IPv6 interface."

#: core/api/pydantic_messages.py:111
msgid "value is not a valid IPv4 or IPv6 network"
msgstr "Value is not a valid IPv4 or IPv6 network."

#: core/api/pydantic_messages.py:113
msgid "value is not a valid IPv4 address"
msgstr "Value is not a valid IPv4 address."

#: core/api/pydantic_messages.py:114
msgid "value is not a valid IPv6 address"
msgstr "Value is not a valid IPv6 address."

#: core/api/pydantic_messages.py:115
msgid "value is not a valid IPv4 network"
msgstr "Value is not a valid IPv4 network."

#: core/api/pydantic_messages.py:116
msgid "value is not a valid IPv6 network"
msgstr "Value is not a valid IPv6 network."

#: core/api/pydantic_messages.py:117
msgid "value is not a valid IPv4 interface"
msgstr "Value is not a valid IPv4 interface."

#: core/api/pydantic_messages.py:118
msgid "value is not a valid IPv6 interface"
msgstr "Value is not a valid IPv6 interface."

#: core/api/pydantic_messages.py:119
msgid "value is not a valid color: {}"
msgstr "Value is not a valid color: {}."

#: core/api/pydantic_messages.py:120
msgid "value is not a valid boolean"
msgstr "Value is not a valid boolean."

#: core/api/pydantic_messages.py:121
msgid "card number is not all digits"
msgstr "Card number is not all digits."

#: core/api/pydantic_messages.py:122
msgid "card number is not luhn valid"
msgstr "Card number is not luhn valid."

#: core/api/pydantic_messages.py:123
msgid "Length for a {}"
msgstr "Length for a {}."

#: core/api/pydantic_messages.py:125
msgid "could not parse value and unit from byte string"
msgstr "Could not parse value and unit from byte string."

#: core/api/pydantic_messages.py:127
msgid "could not interpret byte unit: {}"
msgstr "Could not interpret byte unit: {}."

#: core/api/pydantic_messages.py:128
msgid "Discriminator {} is missing in value"
msgstr "Discriminator {} is missing in value."

#: core/api/pydantic_messages.py:129
msgid "No match for discriminator {}"
msgstr "No match for discriminator {}."

#: core/api/routes.py:27
msgid "Unauthorized"
msgstr "Unauthorized."

#: core/api/routes.py:33
msgid "Internationalization works."
msgstr "Internationalization works."

#: matchmaking/models/invite.py:40 matchmaking/models/lobby.py:410
msgid "Invite not found."
msgstr "Invite not found."

#: matchmaking/models/lobby.py:185 matchmaking/models/lobby.py:242
#: matchmaking/models/lobby.py:361
msgid "User not found."
msgstr "User not found."

#: matchmaking/models/lobby.py:190 matchmaking/models/lobby.py:251
#: matchmaking/models/lobby.py:366
msgid "A verified account is required to perform this action."
msgstr "A verified account is required to perform this action."

#: matchmaking/models/lobby.py:194 matchmaking/models/lobby.py:255
#: matchmaking/models/lobby.py:370
msgid "Offline user."
msgstr "Offline user."

#: matchmaking/models/lobby.py:197 matchmaking/models/lobby.py:469
msgid "The given type is not valid."
msgstr "The given type is not valid."

#: matchmaking/models/lobby.py:203 matchmaking/models/lobby.py:483
msgid "The given mode is not valid."
msgstr "The given mode is not valid."

#: matchmaking/models/lobby.py:237
msgid "Lobby not found."
msgstr "Lobby not found."

#: matchmaking/models/lobby.py:258 matchmaking/models/lobby.py:337
#: matchmaking/models/lobby.py:422 matchmaking/models/lobby.py:446
#: matchmaking/models/lobby.py:455 matchmaking/models/lobby.py:466
#: matchmaking/models/lobby.py:480
msgid "Lobby is queued."
msgstr "Lobby is queued."

#: matchmaking/models/lobby.py:268 matchmaking/models/lobby.py:334
msgid "Lobby is full."
msgstr "Lobby is full."

#: matchmaking/models/lobby.py:354
msgid "Invited user is already a lobby player."
msgstr "Invited user is already a lobby player."

#: matchmaking/models/lobby.py:357
msgid "User already invited."
msgstr "User already invited."

#: matchmaking/models/lobby.py:489
msgid "Owner cannot be removed."
msgstr "Owner cannot be removed."

#: matchmaking/models/team.py:126 matchmaking/models/team.py:138
#, fuzzy
#| msgid "User not found."
msgid "Team not found."
msgstr "Team not found."

#: matchmaking/models/team.py:152
msgid "Team players count exceeded."
msgstr "Team players count exceeded."

#: matchmaking/models/team.py:166 matchmaking/models/team.py:187
msgid "Lobby already on a team."
msgstr "Lobby already on a team."

#: matchmaking/models/team.py:170 matchmaking/models/team.py:191
#, fuzzy
#| msgid "Lobby is queued."
msgid "Lobby not queued."
msgstr "Lobby not queued."
